name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: PR actions/checkout@v2
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: PUSH actions/checkout@v2
        uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.4.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: {python_version}

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: isort - import sorting
        run: |
          pipenv run isort .
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git commit -am "isort: automatic fix of imports" \
          && git push || echo nothing to commit
      - name: black - formatting
        run: |
          pipenv run black .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "black: automated blackening of code"\
          && git push || echo nothing to commit
      - run: pipenv run flake8 .
      - run: pipenv run mypy
      - run: pipenv run pytest --cov --cov-fail-under=100 --cov-report term-missing:skip-covered
