# See https://pre-commit.com/ for usage and config
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: master
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: isort
    name: isort
    language: system
    entry: pipenv run isort
    types: [python]

  - id: black
    name: black
    language: system
    entry: pipenv run black
    types: [python]

  - id: flake8
    name: flake8
    language: system
    entry: pipenv run flake8
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    language: system
    entry: pipenv run mypy
    types: [python]
    exclude: docs/
    require_serial: true

  - id: pytest
    name: pytest
    language: system
    entry: pipenv run pytest
    types: [python]
    pass_filenames: false

  - id: pytest-cov
    name: "pytest coverage"
    stages: [push]
    language: system
    entry: pipenv run pytest --cov --cov-fail-under=100
    types: [python]
    pass_filenames: false

  - id: pipenv-setup-sync
    name: "pipenv-setup sync with pipfile"
    stages: [push]
    language: system
    entry: pipenv run pipenv-setup sync --pipfile
    pass_filenames: false

  - id: pipenv-setup-check
    name: "pipenv-setup check"
    stages: [push]
    language: system
    entry: pipenv run pipenv-setup check
    pass_filenames: false

  - id: pipenv-update-lock
    name: "Update pipfile.lock"
    stages: [push]
    language: system
    entry: pipenv run pipenv update
    pass_filenames: false
